# CryptoManana Framework Scrutinizer CI YAML Configuration

filter:
  paths: [src/CryptoManana/*]
  excluded_paths: [tests/*]

checks:
  php: true

tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  external_code_coverage:
    timeout: 900
