# CryptoManana Framework Scrutinizer CI YAML Configuration

build:
  environment:
    php:
      version: "7.4"

filter:
  paths: [src/CryptoManana/*]
  excluded_paths: [tests/*, vendor/*, src/autoload.php]
  dependency_paths: [src/CryptoManana/Compatibility/*, src/compatibility.php]

checks:
  php: true

tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: "PSR2"
  external_code_coverage:
    timeout: 900
    runs: 2 # <- Zend OPcache ON/OFF
