# CryptoManana Framework Scrutinizer CI YAML Configuration

build:
  nodes:
    analysis:
      image: default-bionic
      environment:
        php:
          version: 8.2
          ini:
            'xdebug.mode': 'coverage'
            'opcache.enable': '1'
            'opcache.enable_cli': '1'
            'default_charset': 'UTF-8'
          pecl_extensions:
            - apcu
      cache:
        directories:
          - vendor/
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
          - command: php check.php
          - command: composer validate
          - command: vendor/bin/phpunit --migrate-configuration
          - command: vendor/bin/phpunit --testdox --coverage-text
            coverage:
              file: coverage/clover.xml
              format: php-clover

filter:
  paths: [src/CryptoManana/*]
  excluded_paths: [tests/*, vendor/*, src/autoload.php]
  dependency_paths: [src/CryptoManana/Compatibility/*, src/compatibility.php]

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 3600
    runs: 2 # 5.6 and 7.4
