# CryptoManana Framework Travis CI YAML Configuration

language: php

os: linux

dist: trusty

env:
  - USE_OPCACHE=1

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

jobs:
  fast_finish: true
  allow_failures:
    - php: master
  include:
    - php: 7.4
      dist: focal
      env:
        - USE_OPCACHE=1
    - php: 8.0
      dist: focal
      env:
        - USE_OPCACHE=1
    - php: 8.1
      dist: focal
      env:
        - USE_OPCACHE=1
    - php: 8.2
      dist: jammy
      addons:
        apt:
          update: true
          packages:
            - libonig-dev
      env:
        - USE_OPCACHE=1
    - php: master
      dist: jammy
      env:
        - USE_OPCACHE=1

cache:
  timeout: 3600
  directories:
    - vendor
    - $HOME/.composer/cache

git:
  depth: 5
  quiet: true

branches:
  only:
    - master
    - staging

before_script:
  - php -m
  - if [ "$USE_OPCACHE" == 1 ]; then
      echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
      echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    fi
  - php -i | grep -i 'OpenSSL Library'
  - php -i | grep -i 'opcache.enable'
  - echo 'sys_temp_dir=/tmp' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'upload_tmp_dir=/tmp' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer validate
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - if [[ "$TRAVIS_PHP_VERSION" =~ ^(7.3|7.4|8.0|8.1|8.2|master)$ ]]; then
      echo 'xdebug.mode=coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
      cp phpunit.xml.dist phpunit.xml;
      vendor/bin/phpunit --migrate-configuration;
    fi

script:
  - make check-system
  - make check-build
  - make coverage

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" =~ ^(5.6|7.4)$ ]]; then
      CLOVER=coverage/clover.xml;
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover ${CLOVER};
    fi
