# CryptoManana Framework Travis CI YAML Configuration

language: php

dist: trusty

sudo: false

env:
  - CLOVER=coverage/clover.xml

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - 7.4snapshot
# - nightly # <- PHP 8.0.0-dev, No support for PHPUnit yet
# - master  # <- PHP 8.0.0-dev, No support for PHPUnit yet

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot # <- PHP 7.4.0-dev (Zend Engine v3.4.0-dev)

cache:
  timeout: 900
  directories:
    - vendor
    - $HOME/.composer/cache

git:
  depth: 5
  quiet: true

before_script:
  - php -m
  - php -i | grep -i 'OpenSSL Library'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - make check-system
  - make check-build
  - make coverage

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then php ocular.phar code-coverage:upload --format=php-clover ${CLOVER}; fi
