# CryptoManana Framework Travis CI YAML Configuration

language: php

dist: trusty

sudo: false

env:
  - USE_OPCACHE=0
  - USE_OPCACHE=1

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - master  # <- PHP 8.0.1

matrix:
  fast_finish: true
  allow_failures:
    - php: master # <- PHP 8.0.x-dev (Zend OPcache v8.0.x-dev, Zend Engine v4.0.x-dev), No Xdebug

cache:
  timeout: 3600
  directories:
    - vendor
    - $HOME/.composer/cache

git:
  depth: 5
  quiet: true

before_script:
  - php -m
  - if [ "$USE_OPCACHE" == 1 ]; then
      echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
      echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
      if [ "$TRAVIS_PHP_VERSION" == "master" ]; then
        echo 'opcache.jit=tracing' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
        echo 'opcache.jit_buffer_size=128M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
        php -i | grep -i 'opcache.jit';
      fi
    fi
  - php -i | grep -i 'OpenSSL Library'
  - php -i | grep -i 'opcache.enable'
  - echo 'sys_temp_dir=/tmp' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'upload_tmp_dir=/tmp' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer validate
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - if [[ "$TRAVIS_PHP_VERSION" =~ ^(7.3|7.4|master)$ ]]; then
      echo 'xdebug.mode=coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
      cp phpunit.xml.dist phpunit.xml;
      vendor/bin/phpunit --migrate-configuration;
    fi

script:
  - make check-system
  - make check-build
  - make coverage

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then
      CLOVER=coverage/clover.xml;
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover ${CLOVER};
    fi
